services:
  app:
    image: ${NETGO_IMAGE}
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb:11.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - netgo_db:/var/lib/mysql

volumes:
  netgo_db:
